Fix Consumer Memory Leak: Hanging promises
ayeo-flex-org/pulsar-flex pull request #80
Opened 2021-12-21 09:52 UTC by ronfarkash

Fixes #79 

`await process()` will never be resolved due to the function calling itself again and again causing unused references to dequeued messages to stay alive, resulting in a memory leak.

Made process() call asynchronous and added `return` when the function ends.

2021-12-21 10:15 UTC, galrose approved these changes
LGTM

2021-12-22 07:52 UTC, danielsinai requested changes

2021-12-22 08:58 UTC, galrose commented on src/consumer/index.js
> +      process();
Good idea, nice catch

2021-12-26 05:48 UTC, ronfarkash commented on src/consumer/index.js
> +      process();
Should be done now.

2022-01-04 07:51 UTC, merged