feat(producer): allow disabling pendingMessagesQueue
ayeo-flex-org/pulsar-flex pull request #88
Opened 2022-12-05 09:18 UTC by Eywek

2022-12-05 09:27 UTC, galrose requested changes
LGTM, could you just add a test for the happy flow of writing with the queue size on zero?
Just to make sure its not broken in the future

2022-12-05 14:39 UTC, Eywek commented
> LGTM, could you just add a test for the happy flow of writing with the queue size on zero? Just to make sure its not broken in the future

done!

2022-12-06 08:59 UTC, galrose requested changes

2022-12-06 08:59 UTC, galrose commented on test/producer/index-spec.js
> +    it('should not throw exception', async function () {
The test you created checks that you catch the error it doesn't check that data was sent using the producer, some of the tests above test actual sending. For example, the it 'should resend messages after unload' test is a simple test that checks sending messages. (You don't need to unload just check that sending messages works in  general.)
Can you rename the describe and the it to something more intuitive to what the test does and specifically about the queue size being 0?

2024-08-17 13:49 UTC, closed without merging